apiVersion: iam.flexibleengine.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/role
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    description: created by terraform
    name: test
    policy: |
      {
        "Version": "1.1",
        "Statement": [
          {
            "Action": [
              "obs:bucket:GetBucketAcl"
            ],
            "Effect": "Allow",
            "Resource": [
              "obs:*:*:bucket:*"
            ],
            "Condition": {
              "StringStartWith": {
                "g:ProjectName": [
                  "eu-west-0"
                ]
              }
            }
          }
        ]
      }
    type: AX

---

