apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: PeeringConnection
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/peering
  labels:
    testing.upbound.io/example-name: example-peering
  name: example-peering
spec:
  forProvider:
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-vpc
    peerVpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-vpc-2
    name: "example-peering"
# ---
# apiVersion: vpc.flexibleengine.upbound.io/v1beta1
# kind: PeeringConnectionAccepter
# metadata:
#   annotations:
#     meta.upbound.io/example-id: vpc/v1beta1/peering
#   labels:
#     testing.upbound.io/example-name: example-peering-accepter
#   name: example-peering-accepter
# spec:
#   forProvider:
#     vpcPeeringConnectionIdSelector:
#       matchLabels:
#         testing.upbound.io/example-name: example-peering
#     accept: true