apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: PeeringConnection
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/peering
  labels:
    testing.upbound.io/example-name: example_vpc_peering
  name: example-vpc-peering
spec:
  forProvider:
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_vpc_peering_vpc_1
    peerVpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_vpc_peering_vpc_2
    name: "example-vpc-peering"
