apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: PeeringConnectionAccepter
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/peeringconnectionaccepter
  labels:
    testing.upbound.io/example-name: example_vpc_peeringconnectionaccepter
  name: example-vpc-peeringconnectionaccepter
spec:
  providerConfigRef:
    name: externe
  forProvider:
    accept: true
    vpcPeeringConnectionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_vpc_peeringconnection
