apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: Port
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/port
  labels:
    testing.upbound.io/example-name: port_1
  name: port-1
spec:
  forProvider:
    adminStateUp: true
    name: port_1
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_1
---
apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/port
  labels:
    testing.upbound.io/example-name: network_1
  name: network-1
spec:
  forProvider:
    adminStateUp: "true"
    name: network_1
---
