apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: Port
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/port
  labels:
    testing.upbound.io/example-name: example_port
  name: example-port
spec:
  forProvider:
    adminStateUp: true
    name: example-vpc
    fixedIp:
      - ipAddress: 192.168.100.100
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example_subnet
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet
