apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: Router
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/router
  labels:
    testing.upbound.io/example-name: example_router
  name: example-router
spec:
  forProvider:
    name: example-router
