apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/securitygroup
  labels:
    testing.upbound.io/example-name: example_secgroup
  name: example-secgroup
spec:
  forProvider:
    description: My example security group
    name: example-secgroup
