apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/securitygrouprule
  labels:
    testing.upbound.io/example-name: example_secgroup_rule
  name: example-secgroup-rule
spec:
  forProvider:
    direction: ingress
    ethertype: IPv4
    portRangeMax: 22
    portRangeMin: 22
    protocol: tcp
    remoteIpPrefix: 0.0.0.0/0
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_secgroup
