apiVersion: vpc.flexibleengine.upbound.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vpc
  labels:
    testing.upbound.io/example-name: example-vpc
  name: example-vpc
spec:
  forProvider:
    name: "example-vpc"
    cidr: "10.2.3.0/24"

--- 
apiVersion: vpc.flexibleengine.upbound.io/v1alpha1
kind: VPCSubnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/subnet
  labels:
    testing.upbound.io/example-name: example-subnet
  name: example-subnet
spec:
  forProvider:
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-vpc
    name: "example-subnet"
    cidr: "10.2.3.0/28"
    gatewayIp: "10.2.3.1"
