apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: Vip
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vip
  labels:
    testing.upbound.io/example-name: vip_1
  name: vip-1
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_1
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_1
---
apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vip
  labels:
    testing.upbound.io/example-name: network_1
  name: network-1
spec:
  forProvider:
    adminStateUp: "true"
    name: network_1
---
apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: NetworkingSubnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vip
  labels:
    testing.upbound.io/example-name: subnet_1
  name: subnet-1
spec:
  forProvider:
    cidr: 192.168.199.0/24
    ipVersion: 4
    name: subnet_1
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_1
---
