apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VIP
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vip
  labels:
    testing.upbound.io/example-name: vip_1
  name: vip-1
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet