apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VIPAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vipassociate
  labels:
    testing.upbound.io/example-name: example_vip_associate
  name: example-vip-associate
spec:
  forProvider:
    portIdsSelector:
      matchLabels:
        testing.upbound.io/example-name: example_port
    vipIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_vip
