apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VIPAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vipassociate
  labels:
    testing.upbound.io/example-name: vip_associate_1
  name: vip-associate-1
spec:
  forProvider:
    portIdsSelector:
      matchLabels:
        testing.upbound.io/example-name: port_1
    vipIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vip_1