apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vpc
  labels:
    testing.upbound.io/example-name: example_vpc
  name: example-vpc
spec:
  forProvider:
    name: "example-vpc"
    cidr: "192.168.0.0/16"