apiVersion: vpc.flexibleengine.upbound.io/v1alpha1
kind: Vpc
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1beta1/vpc
  labels:
    testing.upbound.io/example-name: example-vpc
  name: example-vpc
spec:
  forProvider:
    name: "example-vpc"
    cidr: "10.2.3.0/24"
