apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VPCSubnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vpcsubnet
  labels:
    testing.upbound.io/example-name: example_subnet
  name: example-subnet
spec:
  forProvider:
    cidr: "192.168.0.0/24"
    gatewayIp: "192.168.0.1"
    name: "example-subnet"
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_vpc