apiVersion: cce.flexibleengine.upbound.io/v1beta1
kind: CCENameSpace
metadata:
  annotations:
    meta.upbound.io/example-id: cce/v1beta1/ccenamespace
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: test-namespace

---

