apiVersion: cce.flexibleengine.upbound.io/v1beta1
kind: Namespace
metadata:
  annotations:
    meta.upbound.io/example-id: cce/v1beta1/namespace
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterId: ${var.cluster_id}
    name: test-namespace

---

