apiVersion: cce.flexibleengine.upbound.io/v1beta1
kind: Pvc
metadata:
  annotations:
    meta.upbound.io/example-id: cce/v1beta1/pvc
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessModes:
    - ReadWriteOnce
    annotations:
      everest.io/disk-volume-type: SSD
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: ${var.pvc_name}
    namespaceSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storage: 10Gi
    storageClassName: csi-disk

---

