apiVersion: iam.flexibleengine.upbound.io/v1beta1
kind: GroupMembership
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/groupmembership
  labels:
    testing.upbound.io/example-name: membership_1
  name: membership-1
spec:
  forProvider:
    groupSelector:
      matchLabels:
        testing.upbound.io/example-name: group_1
    usersRefs:
    - name: user-1
    - name: user-2