apiVersion: iam.flexibleengine.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/group
  labels:
    testing.upbound.io/example-name: group_1
  name: group-1
spec:
  forProvider:
    description: This is a test group
    name: group_1