apiVersion: iam.flexibleengine.upbound.io/v1beta1
kind: RoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/roleassignment
  labels:
    testing.upbound.io/example-name: role_assignment_1
  name: role-assignment-1
spec:
  forProvider:
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: group_1
    domainId: 9e2d8c6bfd704d5784205410d07ac0b3
    roleIdSelector:
      matchLabels:
        testing.upbound.io/example-name: role