apiVersion: iam.flexibleengine.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/user
  labels:
    testing.upbound.io/example-name: example_user
  name: example-user
spec:
  forProvider: {}
