apiVersion: lts.flexibleengine.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: lts/v1beta1/group
  labels:
    testing.upbound.io/example-name: example_lts_group
  name: example-lts-group
spec:
  forProvider:
    groupName: example-lts-group
