apiVersion: lts.flexibleengine.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: lts/v1beta1/topic
  labels:
    testing.upbound.io/example-name: example_lts_topic
  name: example-lts-topic
spec:
  forProvider:
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_lts_group
    topicName: example-lts-topic
