apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VIP
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vip
  labels:
    testing.upbound.io/example-name: vip_1
  name: vip-1
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_1

---

apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VPCSubnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vip
  labels:
    testing.upbound.io/example-name: subnet_1
  name: subnet-1
spec:
  forProvider:
    cidr: ${var.subnet_cidr}
    gatewayIp: ${var.subnet_gateway_ip}
    name: ${var.subnet_name}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc_1

---

apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vip
  labels:
    testing.upbound.io/example-name: vpc_1
  name: vpc-1
spec:
  forProvider:
    cidr: ${var.vpc_cidr}
    name: ${var.vpc_name}

---

