apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VIPAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vipassociate
  labels:
    testing.upbound.io/example-name: vip_associate_1
  name: vip-associate-1
spec:
  forProvider:
    portIdsRefs:
    - name: server_1
    - name: server_2
    vipIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vip_1

---

apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vipassociate
  labels:
    testing.upbound.io/example-name: server_1
  name: server-1
spec:
  forProvider:
    name: instance_1
    network:
    - uuidSelector:
        matchLabels:
          testing.upbound.io/example-name: example_subnet

---

apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vipassociate
  labels:
    testing.upbound.io/example-name: server_2
  name: server-2
spec:
  forProvider:
    name: instance_2
    network:
    - uuidSelector:
        matchLabels:
          testing.upbound.io/example-name: example_subnet

---

apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VIP
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vipassociate
  labels:
    testing.upbound.io/example-name: vip_1
  name: vip-1
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet

---

