apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VPCSubnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vpcsubnet
  labels:
    testing.upbound.io/example-name: subnet_v1
  name: subnet-v1
spec:
  forProvider:
    cidr: ${var.subnet_cidr}
    gatewayIp: ${var.subnet_gateway_ip}
    name: ${var.subnet_name}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc_v1

---

apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vpcsubnet
  labels:
    testing.upbound.io/example-name: vpc_v1
  name: vpc-v1
spec:
  forProvider:
    cidr: ${var.vpc_cidr}
    name: ${var.vpc_name}

---

