apiVersion: mls.flexibleengine.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: mls/v1beta1/instance
  labels:
    testing.upbound.io/example-name: instance
  name: instance
spec:
  forProvider:
    flavor: mls.c2.2xlarge.common
    mrsCluster:
    - id: ${flexibleengine_mrs_cluster_v1.cluster1.id}
    name: terraform-mls-instance
    network:
    - availableZone: eu-west-0a
      publicIp:
      - bindType: not_use
      subnetId: b65f8d25-c533-47e2-8601-cfaa265a3e3e
      vpcId: c1095fe7-03df-4205-ad2d-6f4c181d436e
    version: 1.2.0

---

apiVersion: mrs.flexibleengine.upbound.io/v1beta1
kind: MrsClusterD
metadata:
  annotations:
    meta.upbound.io/example-id: mls/v1beta1/instance
  labels:
    testing.upbound.io/example-name: cluster1
  name: cluster1
spec:
  forProvider:
    availableZoneId: eu-west-0a
    billingType: 12
    clusterAdminSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    clusterName: mrs-cluster-acc
    clusterType: 0
    clusterVersion: MRS 1.3.0
    componentList:
    - componentName: Hadoop
    - componentName: Spark
    - componentName: Hive
    coreNodeNum: 3
    coreNodeSize: s1.xlarge.linux.mrs
    masterNodeNum: 2
    masterNodeSize: s1.4xlarge.linux.mrs
    nodePublicCertName: KeyPair-ci
    region: eu-west-0
    safeMode: 0
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    volumeSize: 100
    volumeType: SATA
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

