apiVersion: cce.flexibleengine.upbound.io/v1beta1
kind: Node
metadata:
  annotations:
    meta.upbound.io/example-id: cce/v1beta1/node
  labels:
    testing.upbound.io/example-name: example_cce_node
  name: example-cce-node
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_cce_cluster
    name: example-cce-node
    flavorId: s3.large.2
    availabilityZone: eu-west-0a
    keyPairSelector:
      matchLabels:
        testing.upbound.io/example-name: example_keypair
    dataVolumes:
      - size: 100
        volumetype: SATA
    rootVolume:
      - size: 40
        volumetype: SATA