apiVersion: elb.flexibleengine.upbound.io/v1beta1
kind: Member
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/member
  labels:
    testing.upbound.io/example-name: member_1
  name: member-1
spec:
  forProvider:
    address: 192.168.199.23
    poolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    protocolPort: 8080
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

