apiVersion: kms.flexibleengine.upbound.io/v1beta1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/key
  labels:
    testing.upbound.io/example-name: key_1
  name: key-1
spec:
  forProvider:
    isEnabled: true
    keyAlias: key_1
    keyDescription: first test key
    pendingDays: "7"
    realm: cn-north-1

---

