apiVersion: oss.flexibleengine.upbound.io/v1beta1
kind: S3BucketPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1beta1/s3bucketpolicy
  labels:
    testing.upbound.io/example-name: b
  name: b
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: b
    policy: "{\n  \"Version\": \"2012-10-17\",\n  \"Id\": \"MYBUCKETPOLICY\",\n  \"Statement\":
      [\n    {\n      \"Sid\": \"IPAllow\",\n      \"Effect\": \"Deny\",\n      \"Principal\":
      \"*\",\n      \"Action\": \"s3:*\",\n      \"Resource\": \"arn:aws:s3:::my_tf_test_bucket/*\",\n
      \     \"Condition\": {\n         \"IpAddress\": {\"aws:SourceIp\": \"8.8.8.8/32\"}\n
      \     } \n    } \n  ]\n}\n"

---

apiVersion: oss.flexibleengine.upbound.io/v1beta1
kind: S3Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1beta1/s3bucketpolicy
  labels:
    testing.upbound.io/example-name: b
  name: b
spec:
  forProvider:
    bucket: my_tf_test_bucket

---

