apiVersion: rts.flexibleengine.upbound.io/v1beta1
kind: SoftwareConfig
metadata:
  annotations:
    meta.upbound.io/example-id: rts/v1beta1/softwareconfig
  labels:
    testing.upbound.io/example-name: myconfig
  name: myconfig
spec:
  forProvider:
    name: ${var.config_name}

---

