apiVersion: vpcep.flexibleengine.upbound.io/v1beta1
kind: Endpoint
metadata:
  annotations:
    meta.upbound.io/example-id: vpcep/v1beta1/endpoint
  labels:
    testing.upbound.io/example-name: example_vpcep_endpoint
  name: example-vpcep-endpoint
spec:
  forProvider:
    enableDns: true
    enableWhitelist: true
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet
    serviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_vpcep_service
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_vpc
