apiVersion: v1
kind: Secret
metadata:
  labels:
    testing.upbound.io/example-name: example_rds_secret
  name: example-rds-secret
  namespace: crossplane-system
type: Opaque
stringData:
  example-rds-key: SuperS3cr3tP4ssw0rd