apiVersion: rds.flexibleengine.upbound.io/v1beta1
kind: ReadReplica
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/readreplica
  labels:
    testing.upbound.io/example-name: example_rds_readreplica
  name: example-rds-readreplica
spec:
  forProvider:
    availabilityZone: eu-west-0c
    flavor: rds.mysql.s3.medium.4.rr
    name: example-rds-readreplica
    replicaOfIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_rds_instance
    volume:
    - type: ULTRAHIGH