apiVersion: nat.flexibleengine.upbound.io/v1beta1
kind: SnatRule
metadata:
  annotations:
    meta.upbound.io/example-id: nat/v1beta1/snatrule
  labels:
    testing.upbound.io/example-name: snat_1
  name: snat-1
spec:
  forProvider:
    floatingIpIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    natGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

