apiVersion: eip.flexibleengine.upbound.io/v1beta1
kind: EIPAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1beta1/eipassociate
  labels:
    testing.upbound.io/example-name: associated
  name: associated
spec:
  forProvider:
    fixedIp: 192.168.0.100
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    publicIpSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

