apiVersion: elb.flexibleengine.upbound.io/v1beta1
kind: L7Policy
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/l7policy
  labels:
    testing.upbound.io/example-name: example_l7policy
  name: example-l7policy
spec:
  forProvider:
    action: REDIRECT_TO_POOL
    description: test l7 policy
    listenerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_listener
    redirectPoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_pool
    name: test
    position: 1