apiVersion: elb.flexibleengine.upbound.io/v1beta1
kind: L7Rule
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/l7rule
  labels:
    testing.upbound.io/example-name: example_l7rule
  name: example-l7rule
spec:
  forProvider:
    compareType: EQUAL_TO
    l7policyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_l7policy
    type: PATH
    value: /api