apiVersion: elb.flexibleengine.upbound.io/v1beta1
kind: Member
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/member
  labels:
    testing.upbound.io/example-name: example_member
  name: example-member
spec:
  forProvider:
    address: 192.168.0.130
    poolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_pool
    protocolPort: 8080
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet
---
apiVersion: elb.flexibleengine.upbound.io/v1beta1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/pool
  labels:
    testing.upbound.io/example-name: example_pool
  name: example-pool
spec:
  forProvider:
    lbMethod: ROUND_ROBIN
    listenerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_listener
    persistence:
    - cookieName: testCookie
      type: APP_COOKIE
    protocol: HTTP
---
apiVersion: elb.flexibleengine.upbound.io/v1beta1
kind: Listener
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/listener
  labels:
    testing.upbound.io/example-name: example_listener
  name: example-listener
spec:
  forProvider:
    loadbalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_lb
    protocol: HTTP
    protocolPort: 8080
    tags:
      key: value
---
apiVersion: elb.flexibleengine.upbound.io/v1beta1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/loadbalancer
  labels:
    testing.upbound.io/example-name: example_lb
  name: example-lb
spec:
  forProvider:
    tags:
      key: value
    vipSubnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet
---