apiVersion: elb.flexibleengine.upbound.io/v1beta1
kind: Member
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/member
  labels:
    testing.upbound.io/example-name: example_member
  name: example-member
spec:
  forProvider:
    address: 192.168.0.130
    poolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_pool
    protocolPort: 8080
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet