apiVersion: elb.flexibleengine.upbound.io/v1beta1
kind: Monitor
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/monitor
  labels:
    testing.upbound.io/example-name: example_monitor
  name: example-monitor
spec:
  forProvider:
    delay: 20
    maxRetries: 5
    poolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_pool
    timeout: 10
    type: PING