apiVersion: elb.flexibleengine.upbound.io/v1beta1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/pool
  labels:
    testing.upbound.io/example-name: example_pool
  name: example-pool
spec:
  forProvider:
    lbMethod: ROUND_ROBIN
    listenerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_listener
    persistence:
      - cookieName: testCookie
        type: APP_COOKIE
    protocol: HTTP