apiVersion: agd.flexibleengine.upbound.io/v1beta1
kind: Response
metadata:
  annotations:
    meta.upbound.io/example-id: agd/v1beta1/response
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: ${var.response_name}
    rule:
    - body: '{"code":"$context.authorizer.frontend.code","message":"$context.authorizer.frontend.message"}'
      errorType: AUTHORIZER_FAILURE
      statusCode: 401

---

