apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: FloatingIpAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/floatingipassociate
  labels:
    testing.upbound.io/example-name: example_ecs_floatingipassociate
  name: example-ecs-floatingipassociate
spec:
  forProvider:
    floatingIpSelector:
      matchLabels:
        testing.upbound.io/example-name: example_eip
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_instance
