apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: ServerGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/servergroup
  labels:
    testing.upbound.io/example-name: example_servergroup
  name: example-servergroup
spec:
  forProvider:
    name: example-servergroup
    policies: ["anti-affinity"]
---
apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: KeyPair
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/keypair
  labels:
    testing.upbound.io/example-name: example_keypair
  name: example-keypair
spec:
  forProvider:
    publicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7CnfqUmkT7aVeJnnCzSXRIMX547BnWRD4V+5SJHnY9zyvi3lC0fLlyZ6MAosdBo77KLMGI45VRHGPwiqmimF6L/O4VG/Ku8xfBXVV0EGilEicbyzvyG26H0O2JDSbIN8AwgDC89Zla2NhQoh7XogK311pkEjK9q2/cVaeeY27S5053FPeFCKedw6q3Dv/naJQbGDqgkShybpccG0jloGalCmDXWqlvSCqj2TGsdj49AKkX5RaygHkploTv8pUyLwmE/bEZV8NLPsp0lS+ziyIZoGqLMCndrFN5P4z2mPVpzTZ/o3Ppv8YKD/BQdg+bwGl6uQuSe5Mcx+eXBlU/Lw1 Generated-by-Nova"
---
apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/instance
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    flavorId: s3.large.2
    imageId: "121d32ef-80d5-41f8-a940-f227a33d2b2a"
    keyPairSelector:
      matchLabels:
        testing.upbound.io/example-name: example_keypair
    name: basic
    network:
    - uuidSelector:
        matchLabels:
          testing.upbound.io/example-name: subnet_v1
    securityGroups:
    - default
    tags:
      foo: bar
      this: that
    schedulerHints:
    - groupSelector:
        matchLabels:
          testing.upbound.io/example-name: example_servergroup
---
