apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: KeyPair
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/keypair
  labels:
    testing.upbound.io/example-name: example_keypair
  name: example-keypair
spec:
  forProvider:
    publicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkGfb1qge/SmCtHyb4O9Tg7qe1JvYj7DFJSCcKbtKy9k2jbUG82HML/BcdJeiJPes29Tk6lnn4IKdZPrmdZ6aU/Uz+slLonZcVdOaMjjtvdQ+gEwWfZT57D9cqiqAuGFjCW4dTVzsw4heKVMhxoVCKf1Y8MuWu4T7zzQCTi6HTO0WIzEB+Ie1Q2GfLY48fknfoetFpr9b9SbmcCx6JKwO9AX292L01WVuuhtUaGLtyuaUahMgfkRuLUQ5u7OzhmRsKd/G4PZfNWArMxd4khXPbghfbnr6pa19Tw+kUEtPp/MzE8sCfzu/JDnQaHlnG9g0l1mQC7u99V4DiZ8FWsH8Vi8KjjBoRUSNVyJM8wUY5Y5DjqkSiqqVjp2gurtGdvFNuNvS+EI1Pg15aV2nrEfVdmgqCveNlrpQC35tEkiVERjkW798GGOuoDu3jCbbBhzFYyDZXvQA2pRuCq6GTDIPWFuphmjpFmhaBy/rjnClqbmYbB5S+ixJA0EBfeXJTSoKZdjdKlx3WBzlIU7FtCCjPbjEccrdXmGnWnFsZmbEMWH007Q5PHVgWbd1lrIoC24rWRAt/l/E9j+9wHSepOLbKYAW0gJagXcoAl1OAueYGR+zb+8+YLwKHk9Gt8NR9TPOEQ5iyTLl0usj3DLSCyPSe/lydzLEQJgkZkVYLszaA9w== hksr2557@hksr2557-HP-EliteBook-850-G5"