apiVersion: mrs.flexibleengine.upbound.io/v1beta1
kind: Job
metadata:
  annotations:
    meta.upbound.io/example-id: mrs/v1beta1/job
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: ${var.job_name}
    parameters: ${var.access_key} ${var.secret_key} 1 s3a://obs-demo-analysis/input
      s3a://obs-demo-analysis/output
    programParameters:
      --class: com.orange.bigdata.spark.examples.DriverBehavior
    programPath: ${var.program_path}
    type: SparkSubmit

---

