apiVersion: dedicatedelb.flexibleengine.upbound.io/v1beta1
kind: Monitor
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/monitor
  labels:
    testing.upbound.io/example-name: example_monitorv3
  name: example-monitorv3
spec:
  forProvider:
    interval: 30
    maxRetries: 10
    poolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_poolv3
    port: 8080
    protocol: HTTP
    timeout: 15
    urlPath: /api