apiVersion: lts.flexibleengine.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: lts/v1beta1/topic
  labels:
    testing.upbound.io/example-name: test_topic
  name: test-topic
spec:
  forProvider:
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_group
    topicName: test1

---

apiVersion: lts.flexibleengine.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: lts/v1beta1/topic
  labels:
    testing.upbound.io/example-name: test_group
  name: test-group
spec:
  forProvider:
    groupName: test_group

---

