apiVersion: smn.flexibleengine.upbound.io/v1beta1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: smn/v1beta1/subscription
  labels:
    testing.upbound.io/example-name: example_smn_subscription
  name: example-smn-subscription
spec:
  forProvider:
    endpoint: mailtest@gmail.com
    protocol: email
    remark: O&M
    topicUrnSelector:
      matchLabels:
        testing.upbound.io/example-name: example_smn_topic
