apiVersion: rds.flexibleengine.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/account
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: test
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

