apiVersion: rds.flexibleengine.upbound.io/v1beta1
kind: ParameterGroup
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/parametergroup
  labels:
    testing.upbound.io/example-name: pg_1
  name: pg-1
spec:
  forProvider:
    datastore:
    - type: mysql
      version: "5.6"
    description: description_1
    name: pg_1
    values:
      autocommit: "OFF"
      max_connections: "10"

---

