apiVersion: dli.flexibleengine.upbound.io/v1beta1
kind: Queue
metadata:
  annotations:
    meta.upbound.io/example-id: dli/v1beta1/queue
  labels:
    testing.upbound.io/example-name: queue
  name: queue
spec:
  forProvider:
    cuCount: 16
    name: terraform_dli_queue_test
    tags:
      foo: bar
      key: value

---

