apiVersion: dli.flexibleengine.upbound.io/v1beta1
kind: SparkJob
metadata:
  annotations:
    meta.upbound.io/example-id: dli/v1beta1/sparkjob
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    appNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    mainClass: driver_behavior
    maxRetries: 20
    name: ${var.job_name}
    queueNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    specification: B

---

