apiVersion: v1
kind: Secret
metadata:
  labels:
    testing.upbound.io/example-name: example_dds_password
  name: example-dds-password
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: SuperS3cr3tP4ssw0rd?