apiVersion: dds.flexibleengine.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: dds/v1beta1/instance
  labels:
    testing.upbound.io/example-name: example_dds_instance
  name: example-dds-instance
spec:
  forProvider:
    availabilityZone: eu-west-0a
    backupStrategy:
    - keepDays: 8
      startTime: 08:00-09:00
    datastore:
    - storageEngine: wiredTiger
      type: DDS-Community
      version: "3.4"
    flavor:
    - num: 2
      specCode: dds.mongodb.s3.medium.4.mongos
      type: mongos
    - num: 2
      size: 20
      specCode: dds.mongodb.s3.medium.4.shard
      storage: ULTRAHIGH
      type: shard
    - num: 1
      size: 20
      specCode: dds.mongodb.s3.large.2.config
      storage: ULTRAHIGH
      type: config
    mode: Sharding
    name: dds-instance
    passwordSecretRef:
      key: credentials
      name: example-dds-password
      namespace: crossplane-system
    region: eu-west-0
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_secgroup
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_vpc