apiVersion: smn.flexibleengine.upbound.io/v1beta1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: smn/v1beta1/subscription
  labels:
    testing.upbound.io/example-name: subscription_1
  name: subscription-1
spec:
  forProvider:
    endpoint: mailtest@gmail.com
    protocol: email
    remark: O&M
    topicUrn: ${flexibleengine_smn_topic_v2.topic_1.id}

---

apiVersion: smn.flexibleengine.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: smn/v1beta1/subscription
  labels:
    testing.upbound.io/example-name: topic_1
  name: topic-1
spec:
  forProvider:
    displayName: The display name of topic_1

---

