/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type InterfaceAttachObservation struct {

	// The IP address associated to the port.
	FixedIP *string `json:"fixedIp,omitempty" tf:"fixed_ip,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the Network associated to the port.
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`
}

type InterfaceAttachParameters struct {

	// The ID of the Instance to attach the Port or Network to.
	// +crossplane:generate:reference:type=github.com/FrangipaneTeam/provider-flexibleengine/apis/ecs/v1beta1.Instance
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in ecs to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in ecs to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The ID of the Port to attach to an Instance.
	// +crossplane:generate:reference:type=github.com/FrangipaneTeam/provider-flexibleengine/apis/vpc/v1beta1.Port
	// +kubebuilder:validation:Optional
	PortID *string `json:"portId,omitempty" tf:"port_id,omitempty"`

	// Reference to a Port in vpc to populate portId.
	// +kubebuilder:validation:Optional
	PortIDRef *v1.Reference `json:"portIdRef,omitempty" tf:"-"`

	// Selector for a Port in vpc to populate portId.
	// +kubebuilder:validation:Optional
	PortIDSelector *v1.Selector `json:"portIdSelector,omitempty" tf:"-"`

	// The region in which to create the interface attachment.
	// If omitted, the region argument of the provider is used. Changing this creates a new attachment.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// InterfaceAttachSpec defines the desired state of InterfaceAttach
type InterfaceAttachSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     InterfaceAttachParameters `json:"forProvider"`
}

// InterfaceAttachStatus defines the observed state of InterfaceAttach.
type InterfaceAttachStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InterfaceAttachObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// InterfaceAttach is the Schema for the InterfaceAttachs API. ""page_title: "flexibleengine_compute_interface_attach_v2"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,flexibleengine}
type InterfaceAttach struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              InterfaceAttachSpec   `json:"spec"`
	Status            InterfaceAttachStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InterfaceAttachList contains a list of InterfaceAttachs
type InterfaceAttachList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InterfaceAttach `json:"items"`
}

// Repository type metadata.
var (
	InterfaceAttach_Kind             = "InterfaceAttach"
	InterfaceAttach_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InterfaceAttach_Kind}.String()
	InterfaceAttach_KindAPIVersion   = InterfaceAttach_Kind + "." + CRDGroupVersion.String()
	InterfaceAttach_GroupVersionKind = CRDGroupVersion.WithKind(InterfaceAttach_Kind)
)

func init() {
	SchemeBuilder.Register(&InterfaceAttach{}, &InterfaceAttachList{})
}
