apiVersion: dms.flexibleengine.upbound.io/v1beta1
kind: RocketMQTopic
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1beta1/rocketmqtopic
  labels:
    testing.upbound.io/example-name: example_dms_rocketmq_topic
  name: example-dms-rocketmq-topic
spec:
  forProvider:
    brokers:
    - name: broker-0
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_dms_rocketmq_instance
    name: topic_test
    permission: all
    queueNum: 3