apiVersion: dms.flexibleengine.upbound.io/v1beta1
kind: RocketMQConsumerGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1beta1/rocketmqconsumergroup
  labels:
    testing.upbound.io/example-name: example_dms_rocketmq_consumergroup
  name: example-dms-rocketmq-consumergroup
spec:
  forProvider:
    broadcast: true
    brokers:
    - broker-0
    enabled: true
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_dms_rocketmq_instance
    name: consumer_group_test
    retryMaxTimes: 3