apiVersion: mrs.flexibleengine.upbound.io/v1beta1
kind: MrsClusterD
metadata:
  annotations:
    meta.upbound.io/example-id: mrs/v1beta1/mrsclusterd
  labels:
    testing.upbound.io/example-name: cluster1
  name: cluster1
spec:
  forProvider:
    availableZoneId: eu-west-0a
    clusterAdminSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    clusterName: mrs-cluster-test
    clusterType: 0
    clusterVersion: MRS 2.0.1
    componentList:
    - componentName: Hadoop
    - componentName: Spark
    - componentName: Hive
    - componentName: Tez
    coreNodeNum: 3
    coreNodeSize: s3.xlarge.4.linux.mrs
    masterNodeNum: 2
    masterNodeSize: s3.2xlarge.4.linux.mrs
    nodePublicCertName: KeyPair-ci
    region: eu-west-0
    safeMode: 0
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    volumeSize: 100
    volumeType: SATA
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

