apiVersion: waf.flexibleengine.upbound.io/v1beta1
kind: Domain
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1beta1/domain
  labels:
    testing.upbound.io/example-name: domain_1
  name: domain-1
spec:
  forProvider:
    certificateIdSelector:
      matchLabels:
        testing.upbound.io/example-name: certificate_1
    domain: www.example.com
    proxy: true
    server:
    - address: 90.84.181.77
      clientProtocol: HTTPS
      port: "8080"
      serverProtocol: HTTP
    sipHeaderList:
    - X-Forwarded-For
    sipHeaderName: default

---

apiVersion: waf.flexibleengine.upbound.io/v1beta1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1beta1/domain
  labels:
    testing.upbound.io/example-name: certificate_1
  name: certificate-1
spec:
  forProvider:
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIFazCCA1OgAwIBAgIUN3w1KX8/T/HWVxZIOdHXPhUOnsAwDQYJKoZIhvcNAQEL
      BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
      ...
      dKvZbPEsygYRIjwyhHHUh/YXH8KDI/uu6u6AxDckQ3rP1BkkKXr5NPBGjVgM3ZI=
      -----END CERTIFICATE-----
    name: cert_1
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQC+9uwFVenCdPD9
      5LWSWMuy4riZW718wxBpYV5Y9N8nM7N0qZLLdpImZrzBbaBldTI+AZGI3Nupuurw
      ...
      s9urs/Kk/tbQhsEvu0X8FyGwo0zH6rG8apTFTlac+v4mJ4vlpxSvT5+FW2lgLISE
      +4sM7kp0qO3/p+45HykwBY5iHq3H
      -----END PRIVATE KEY-----

---

