apiVersion: waf.flexibleengine.upbound.io/v1beta1
kind: RuleDataMasking
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1beta1/ruledatamasking
  labels:
    testing.upbound.io/example-name: rule_1
  name: rule-1
spec:
  forProvider:
    field: params
    path: /login
    policyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: policy_1
    subfield: password

---

apiVersion: waf.flexibleengine.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1beta1/ruledatamasking
  labels:
    testing.upbound.io/example-name: policy_1
  name: policy-1
spec:
  forProvider:
    name: policy_1

---

