apiVersion: as.flexibleengine.upbound.io/v1beta1
kind: Configuration
metadata:
  annotations:
    meta.upbound.io/example-id: as/v1beta1/configuration
  labels:
    testing.upbound.io/example-name: example_as_config
  name: example-as-config
spec:
  forProvider:
    instanceConfig:
      - disk:
          - diskType: SYS
            size: 40
            volumeType: SATA
        flavor: t2.micro
        image: 21d32ef-80d5-41f8-a940-f227a33d2b2a
        keyName: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5BBAAIOC/tpbp4huh1Y0yzhdxoHGQ+17FhZk/vVIEe6vaGAMQ example@example"
    scalingConfigurationName: example-as-config
