apiVersion: as.flexibleengine.upbound.io/v1beta1
kind: Configuration
metadata:
  annotations:
    meta.upbound.io/example-id: as/v1beta1/configuration
  labels:
    testing.upbound.io/example-name: example_as_config
  name: example-as-config
spec:
  forProvider:
    instanceConfig:
      - disk:
          - diskType: SYS
            size: 40
            volumeType: SATA
        flavor: t2.micro
        imageSelector:
          matchLabels:
            testing.upbound.io/example-name: example_ims_image
        keyNameSelector:
          matchLabels:
            testing.upbound.io/example-name: example_keypair
    scalingConfigurationName: example-as-config
