/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ListenerObservation struct {
<<<<<<< HEAD

	// The unique ID for the listener.
=======
>>>>>>> 073fca432c54112a5bd069d5eba77a07c6045db5
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ListenerParameters struct {

<<<<<<< HEAD
	// Specifies the access policy for the listener. Valid options are white and
	// black.
	// +kubebuilder:validation:Optional
	AccessPolicy *string `json:"accessPolicy,omitempty" tf:"access_policy,omitempty"`

	// Specifies whether to enable advanced forwarding.
	// If advanced forwarding is enabled, more flexible forwarding policies and rules are supported.
	// +kubebuilder:validation:Optional
	AdvancedForwardingEnabled *bool `json:"advancedForwardingEnabled,omitempty" tf:"advanced_forwarding_enabled,omitempty"`

	// Specifies the ID of the CA certificate used by the listener.
	// This parameter is valid when protocol is set to HTTPS.
=======
	// +kubebuilder:validation:Optional
	AccessPolicy *string `json:"accessPolicy,omitempty" tf:"access_policy,omitempty"`

	// +kubebuilder:validation:Optional
	AdvancedForwardingEnabled *bool `json:"advancedForwardingEnabled,omitempty" tf:"advanced_forwarding_enabled,omitempty"`

>>>>>>> 073fca432c54112a5bd069d5eba77a07c6045db5
	// +crossplane:generate:reference:type=Certificate
	// +kubebuilder:validation:Optional
	CACertificate *string `json:"caCertificate,omitempty" tf:"ca_certificate,omitempty"`

	// Reference to a Certificate to populate caCertificate.
	// +kubebuilder:validation:Optional
	CACertificateRef *v1.Reference `json:"caCertificateRef,omitempty" tf:"-"`

	// Selector for a Certificate to populate caCertificate.
	// +kubebuilder:validation:Optional
	CACertificateSelector *v1.Selector `json:"caCertificateSelector,omitempty" tf:"-"`

<<<<<<< HEAD
	// The ID of the default pool with which the listener is associated. Changing this
	// creates a new listener.
=======
>>>>>>> 073fca432c54112a5bd069d5eba77a07c6045db5
	// +crossplane:generate:reference:type=Pool
	// +kubebuilder:validation:Optional
	DefaultPoolID *string `json:"defaultPoolId,omitempty" tf:"default_pool_id,omitempty"`

	// Reference to a Pool to populate defaultPoolId.
	// +kubebuilder:validation:Optional
	DefaultPoolIDRef *v1.Reference `json:"defaultPoolIdRef,omitempty" tf:"-"`

	// Selector for a Pool to populate defaultPoolId.
	// +kubebuilder:validation:Optional
	DefaultPoolIDSelector *v1.Selector `json:"defaultPoolIdSelector,omitempty" tf:"-"`

<<<<<<< HEAD
	// Human-readable description for the listener.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies whether transfer the load balancer EIP in the X-Forward-EIP header to
	// backend servers. The default value is false. This parameter is valid only when the protocol is set to HTTP or
	// HTTPS.
	// +kubebuilder:validation:Optional
	ForwardEIP *bool `json:"forwardEip,omitempty" tf:"forward_eip,omitempty"`

	// Specifies whether to use HTTP/2. The default value is false. This parameter is valid
	// only when the protocol is set to HTTPS.
	// +kubebuilder:validation:Optional
	Http2Enable *bool `json:"http2Enable,omitempty" tf:"http2_enable,omitempty"`

	// Specifies the ip group id for the listener.
=======
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	ForwardEIP *bool `json:"forwardEip,omitempty" tf:"forward_eip,omitempty"`

	// +kubebuilder:validation:Optional
	Http2Enable *bool `json:"http2Enable,omitempty" tf:"http2_enable,omitempty"`

>>>>>>> 073fca432c54112a5bd069d5eba77a07c6045db5
	// +crossplane:generate:reference:type=IPGroup
	// +kubebuilder:validation:Optional
	IPGroup *string `json:"ipGroup,omitempty" tf:"ip_group,omitempty"`

	// Reference to a IPGroup to populate ipGroup.
	// +kubebuilder:validation:Optional
	IPGroupRef *v1.Reference `json:"ipGroupRef,omitempty" tf:"-"`

	// Selector for a IPGroup to populate ipGroup.
	// +kubebuilder:validation:Optional
	IPGroupSelector *v1.Selector `json:"ipGroupSelector,omitempty" tf:"-"`

<<<<<<< HEAD
	// Specifies the idle timeout for the listener. Value range: 0 to 4000.
	// +kubebuilder:validation:Optional
	IdleTimeout *float64 `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

	// The load balancer on which to provision this listener. Changing this
	// creates a new listener.
=======
	// +kubebuilder:validation:Optional
	IdleTimeout *float64 `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

>>>>>>> 073fca432c54112a5bd069d5eba77a07c6045db5
	// +crossplane:generate:reference:type=LoadBalancer
	// +kubebuilder:validation:Optional
	LoadbalancerID *string `json:"loadbalancerId,omitempty" tf:"loadbalancer_id,omitempty"`

	// Reference to a LoadBalancer to populate loadbalancerId.
	// +kubebuilder:validation:Optional
	LoadbalancerIDRef *v1.Reference `json:"loadbalancerIdRef,omitempty" tf:"-"`

	// Selector for a LoadBalancer to populate loadbalancerId.
	// +kubebuilder:validation:Optional
	LoadbalancerIDSelector *v1.Selector `json:"loadbalancerIdSelector,omitempty" tf:"-"`

<<<<<<< HEAD
	// Human-readable name for the listener.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The protocol can either be TCP, UDP, HTTP or HTTPS.
	// Changing this creates a new listener.
	// +kubebuilder:validation:Required
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`

	// The port on which to listen for client traffic. Changing this creates a
	// new listener.
	// +kubebuilder:validation:Required
	ProtocolPort *float64 `json:"protocolPort" tf:"protocol_port,omitempty"`

	// The region in which to create the listener resource. If omitted, the
	// provider-level region will be used. Changing this creates a new listener.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the request timeout for the listener. Value range: 1 to 300.
	// This parameter is valid when protocol is set to HTTP or HTTPS.
	// +kubebuilder:validation:Optional
	RequestTimeout *float64 `json:"requestTimeout,omitempty" tf:"request_timeout,omitempty"`

	// Specifies the response timeout for the listener. Value range: 1 to 300.
	// This parameter is valid when protocol is set to HTTP or HTTPS.
	// +kubebuilder:validation:Optional
	ResponseTimeout *float64 `json:"responseTimeout,omitempty" tf:"response_timeout,omitempty"`

	// Specifies the ID of the server certificate used by the listener.
	// This parameter is mandatory when protocol is set to HTTPS.
=======
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Required
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`

	// +kubebuilder:validation:Required
	ProtocolPort *float64 `json:"protocolPort" tf:"protocol_port,omitempty"`

	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// +kubebuilder:validation:Optional
	RequestTimeout *float64 `json:"requestTimeout,omitempty" tf:"request_timeout,omitempty"`

	// +kubebuilder:validation:Optional
	ResponseTimeout *float64 `json:"responseTimeout,omitempty" tf:"response_timeout,omitempty"`

>>>>>>> 073fca432c54112a5bd069d5eba77a07c6045db5
	// +crossplane:generate:reference:type=Certificate
	// +kubebuilder:validation:Optional
	ServerCertificate *string `json:"serverCertificate,omitempty" tf:"server_certificate,omitempty"`

	// Reference to a Certificate to populate serverCertificate.
	// +kubebuilder:validation:Optional
	ServerCertificateRef *v1.Reference `json:"serverCertificateRef,omitempty" tf:"-"`

	// Selector for a Certificate to populate serverCertificate.
	// +kubebuilder:validation:Optional
	ServerCertificateSelector *v1.Selector `json:"serverCertificateSelector,omitempty" tf:"-"`

<<<<<<< HEAD
	// Lists the IDs of SNI certificates (server certificates with a domain name) used
	// by the listener. This parameter is valid when protocol is set to HTTPS.
=======
>>>>>>> 073fca432c54112a5bd069d5eba77a07c6045db5
	// +crossplane:generate:reference:type=Certificate
	// +kubebuilder:validation:Optional
	SniCertificate []*string `json:"sniCertificate,omitempty" tf:"sni_certificate,omitempty"`

	// References to Certificate to populate sniCertificate.
	// +kubebuilder:validation:Optional
	SniCertificateRefs []v1.Reference `json:"sniCertificateRefs,omitempty" tf:"-"`

	// Selector for a list of Certificate to populate sniCertificate.
	// +kubebuilder:validation:Optional
	SniCertificateSelector *v1.Selector `json:"sniCertificateSelector,omitempty" tf:"-"`

<<<<<<< HEAD
	// Specifies the TLS cipher policy for the listener. Valid options are:
	// tls-1-0-inherit, tls-1-0, tls-1-1, tls-1-2, tls-1-2-strict, tls-1-2-fs, tls-1-0-with-1-3, and tls-1-2-fs-with-1-3.
	// This parameter is valid when protocol is set to HTTPS.
	// +kubebuilder:validation:Optional
	TLSCiphersPolicy *string `json:"tlsCiphersPolicy,omitempty" tf:"tls_ciphers_policy,omitempty"`

	// The key/value pairs to associate with the listener.
=======
	// +kubebuilder:validation:Optional
	TLSCiphersPolicy *string `json:"tlsCiphersPolicy,omitempty" tf:"tls_ciphers_policy,omitempty"`

>>>>>>> 073fca432c54112a5bd069d5eba77a07c6045db5
	// +kubebuilder:validation:Optional
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// ListenerSpec defines the desired state of Listener
type ListenerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ListenerParameters `json:"forProvider"`
}

// ListenerStatus defines the observed state of Listener.
type ListenerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ListenerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

<<<<<<< HEAD
// Listener is the Schema for the Listeners API. ""page_title: "flexibleengine_lb_listener_v3"
=======
// Listener is the Schema for the Listeners API. <no value>
>>>>>>> 073fca432c54112a5bd069d5eba77a07c6045db5
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,flexibleengine}
type Listener struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ListenerSpec   `json:"spec"`
	Status            ListenerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ListenerList contains a list of Listeners
type ListenerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Listener `json:"items"`
}

// Repository type metadata.
var (
	Listener_Kind             = "Listener"
	Listener_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Listener_Kind}.String()
	Listener_KindAPIVersion   = Listener_Kind + "." + CRDGroupVersion.String()
	Listener_GroupVersionKind = CRDGroupVersion.WithKind(Listener_Kind)
)

func init() {
	SchemeBuilder.Register(&Listener{}, &ListenerList{})
}
