apiVersion: fgs.flexibleengine.upbound.io/v1beta1
kind: Dependency
metadata:
  annotations:
    meta.upbound.io/example-id: fgs/v1beta1/dependency
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    link: ${format("https://%s/%s", flexibleengine_obs_bucket.test.bucket_domain_name,
      flexibleengine_obs_bucket_object.test.key)}
    name: ${var.dependency_name}
    runtime: Python3.6

---

apiVersion: oss.flexibleengine.upbound.io/v1beta1
kind: OBSBucket
metadata:
  annotations:
    meta.upbound.io/example-id: fgs/v1beta1/dependency
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider: {}

---

apiVersion: oss.flexibleengine.upbound.io/v1beta1
kind: OBSBucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: fgs/v1beta1/dependency
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    key: ${format("terraform_dependencies/%s", var.package_name)}
    source: ${var.package_location}

---

