apiVersion: fgs.flexibleengine.upbound.io/v1beta1
kind: Trigger
metadata:
  annotations:
    meta.upbound.io/example-id: fgs/v1beta1/trigger
  labels:
    testing.upbound.io/example-name: example_fgs_trigger
  name: example-fgs-trigger
spec:
  forProvider:
    functionUrnSelector:
      matchLabels:
        testing.upbound.io/example-name: example_fgs_function
    timer:
    - name: example_trigger
      schedule: 1d
      scheduleType: Rate
    type: TIMER