apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: InterfaceAttach
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/interfaceattach
  labels:
    testing.upbound.io/example-name: ai_1
  name: ai-1
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance_1

---

apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/interfaceattach
  labels:
    testing.upbound.io/example-name: instance_1
  name: instance-1
spec:
  forProvider:
    name: instance_1
    securityGroups:
    - default

---

