apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: ServerGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/servergroup
  labels:
    testing.upbound.io/example-name: test-sg
  name: test-sg
spec:
  forProvider:
    name: my-sg
    policies:
    - anti-affinity

---

