apiVersion: dli.flexibleengine.upbound.io/v1beta1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: dli/v1beta1/database
  labels:
    testing.upbound.io/example-name: example_dli_database
  name: example-dli-database
spec:
  forProvider:
    name: exampledlidatabase
