apiVersion: dedicatedelb.flexibleengine.upbound.io/v1beta1
kind: Monitor
metadata:
  annotations:
    meta.upbound.io/example-id: dedicatedelb/v1beta1/monitor
  labels:
    testing.upbound.io/example-name: monitor_1
  name: monitor-1
spec:
  forProvider:
    interval: 30
    maxRetries: 10
    poolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    port: 8888
    protocol: HTTP
    timeout: 15
    urlPath: /api

---

