apiVersion: netacl.flexibleengine.upbound.io/v1beta1
kind: ACLRule
metadata:
  annotations:
    meta.upbound.io/example-id: netacl/v1beta1/aclrule
  labels:
    testing.upbound.io/example-name: rule_1
  name: rule-1
spec:
  forProvider:
    action: deny
    destinationIpAddress: 4.3.2.0/24
    destinationPort: "555"
    name: rule_1
    protocol: udp
    sourceIpAddress: 1.2.3.4
    sourcePort: "444"

---

