apiVersion: netacl.flexibleengine.upbound.io/v1beta1
kind: FirewallGroup
metadata:
  annotations:
    meta.upbound.io/example-id: netacl/v1beta1/firewallgroup
  labels:
    testing.upbound.io/example-name: firewall_group_1
  name: firewall-group-1
spec:
  forProvider:
    ingressPolicyId: ${flexibleengine_fw_policy_v2.policy_1.id}
    name: my-firewall-group

---

apiVersion: netacl.flexibleengine.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: netacl/v1beta1/firewallgroup
  labels:
    testing.upbound.io/example-name: policy_1
  name: policy-1
spec:
  forProvider:
    name: my-policy
    rules:
    - ${flexibleengine_fw_rule_v2.rule_1.id}
    - ${flexibleengine_fw_rule_v2.rule_2.id}

---

apiVersion: netacl.flexibleengine.upbound.io/v1beta1
kind: Rule
metadata:
  annotations:
    meta.upbound.io/example-id: netacl/v1beta1/firewallgroup
  labels:
    testing.upbound.io/example-name: rule_1
  name: rule-1
spec:
  forProvider:
    action: deny
    description: drop TELNET traffic
    destinationPort: "23"
    enabled: "true"
    name: my-rule-1
    protocol: tcp

---

apiVersion: netacl.flexibleengine.upbound.io/v1beta1
kind: Rule
metadata:
  annotations:
    meta.upbound.io/example-id: netacl/v1beta1/firewallgroup
  labels:
    testing.upbound.io/example-name: rule_2
  name: rule-2
spec:
  forProvider:
    action: deny
    description: drop NTP traffic
    destinationPort: "123"
    enabled: "false"
    name: my-rule-2
    protocol: udp

---

