apiVersion: netacl.flexibleengine.upbound.io/v1beta1
kind: Rule
metadata:
  annotations:
    meta.upbound.io/example-id: netacl/v1beta1/rule
  labels:
    testing.upbound.io/example-name: rule_1
  name: rule-1
spec:
  forProvider:
    action: deny
    description: drop TELNET traffic
    destinationPort: "23"
    enabled: "true"
    name: my_rule
    protocol: tcp

---

