apiVersion: nat.flexibleengine.upbound.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.upbound.io/example-id: nat/v1beta1/gateway
  labels:
    testing.upbound.io/example-name: gateway_1
  name: gateway-1
spec:
  forProvider:
    description: test for terraform
    name: example-nat-gw
    spec: "1"
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_v1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc_v1

---

apiVersion: nat.flexibleengine.upbound.io/v1beta1
kind: SnatRule
metadata:
  annotations:
    meta.upbound.io/example-id: nat/v1beta1/snatrule
  labels:
    testing.upbound.io/example-name: snat_1
  name: snat-1
spec:
  forProvider:
    floatingIpIdSelector:
      matchLabels:
        testing.upbound.io/example-name: eip_1
    natGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: gateway_1
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_v1

---

