apiVersion: mrsd.flexibleengine.upbound.io/v1beta1
kind: Job
metadata:
  annotations:
    meta.upbound.io/example-id: mrsd/v1beta1/job
  labels:
    testing.upbound.io/example-name: job1
  name: job1
spec:
  forProvider:
    arguments: wordcount
    clusterId: ef43d2ff-1ecf-4f13-bd0c-0004c429a058
    input: s3a://wordcount/input/
    jarPath: s3a://wordcount/program/hadoop-mapreduce-examples-2.7.5.jar
    jobLog: s3a://wordcount/log/
    jobName: test_mapreduce_job1
    jobType: 1
    output: s3a://wordcount/output/

---

