apiVersion: csbs.flexibleengine.upbound.io/v1beta1
kind: BackupPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: csbs/v1beta1/backuppolicy
  labels:
    testing.upbound.io/example-name: backup_policy_v1
  name: backup-policy-v1
spec:
  forProvider:
    name: backup-policy-v1
    resource:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: basic
      name: backupTest
      type: OS::Nova::Server
    scheduledOperation:
    - enabled: true
      maxBackups: 2
      operationType: backup
      triggerPattern: "BEGIN:VCALENDAR\r\nBEGIN:VEVENT\r\nRRULE:FREQ=WEEKLY;BYDAY=TH;BYHOUR=12;BYMINUTE=27\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n"

---

