apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/vpc
  labels:
    testing.upbound.io/example-name: example-csbs-vpc
  name: example-csbs-vpc
spec:
  forProvider:
    name: "example-csbs-vpc"
    cidr: "10.2.3.0/24"

--- 
apiVersion: vpc.flexibleengine.upbound.io/v1beta1
kind: VPCSubnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1beta1/subnet
  labels:
    testing.upbound.io/example-name: example-csbs-net
  name: example-csbs-net
spec:
  forProvider:
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-csbs-vpc
    name: "example-subnet"
    cidr: "10.2.3.0/28"
    gatewayIp: "10.2.3.1"

---

apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: KeyPair
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/keypair
  labels:
    testing.upbound.io/example-name: example-csbs_keypair
  name: example-csbs-keypair
spec:
  forProvider:
    publicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7CnfqUmkT7aVeJnnCzSXRIMX547BnWRD4V+5SJHnY9zyvi3lC0fLlyZ6MAosdBo77KLMGI45VRHGPwiqmimF6L/O4VG/Ku8xfBXVV0EGilEicbyzvyG26H0O2JDSbIN8AwgDC89Zla2NhQoh7XogK311pkEjK9q2/cVaeeY27S5053FPeFCKedw6q3Dv/naJQbGDqgkShybpccG0jloGalCmDXWqlvSCqj2TGsdj49AKkX5RaygHkploTv8pUyLwmE/bEZV8NLPsp0lS+ziyIZoGqLMCndrFN5P4z2mPVpzTZ/o3Ppv8YKD/BQdg+bwGl6uQuSe5Mcx+eXBlU/Lw1 Generated-by-Nova"

---

apiVersion: ims.flexibleengine.upbound.io/v1beta1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: ims/v1beta1/image
  labels:
    testing.upbound.io/example-name: rancheros
  name: rancheros
spec:
  forProvider:
    containerFormat: bare
    diskFormat: qcow2
    imageSourceUrl: https://releases.rancher.com/os/latest/rancheros-openstack.img
    name: RancherOS

---

apiVersion: ecs.flexibleengine.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/instance
  labels:
    testing.upbound.io/example-name: example-csbs_ecs
  name: example-csbs-ecs
spec:
  forProvider:
    flavorId: t2.micro
    imageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: rancheros
    keyPairSelector:
      matchLabels:
        testing.upbound.io/example-name: example-csbs_keypair 
    name: example-csbs-keypair
    network:
    - uuidSelector:
        matchLabels:
          testing.upbound.io/example-name: example-csbs-net
    securityGroups:
    - default
    tags:
      foo: bar
      this: that

---

apiVersion: csbs.flexibleengine.upbound.io/v1beta1
kind: Backup
metadata:
  annotations:
    meta.upbound.io/example-id: csbs/v1beta1/backup
  labels:
    testing.upbound.io/example-name: backup_v1
  name: backup-v1
spec:
  forProvider:
    backupName: backupTest
    resourceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-csbs_ecs
    resourceType: OS::Nova::Server

---