apiVersion: cse.flexibleengine.upbound.io/v1beta1
kind: MicroserviceInstance
metadata:
  annotations:
    meta.upbound.io/example-id: cse/v1beta1/microserviceinstance
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    connectAddressSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dataCenter:
    - availabilityZone: ${var.az_name}
      name: dc
      region: ${var.region_name}
    endpoints:
    - grpc://127.0.1.132:9980
    - rest://127.0.0.111:8081
    healthCheck:
    - interval: 30
      maxRetries: 3
      mode: push
    hostName: localhost
    microserviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    properties:
      _TAGS: A, B
      attr1: a
      nodeIP: 127.0.0.1
    verison: 1.0.0

---

