apiVersion: cse.flexibleengine.upbound.io/v1beta1
kind: Microservice
metadata:
  annotations:
    meta.upbound.io/example-id: cse/v1beta1/microservice
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    appName: ${var.app_name}
    connectAddressSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    environment: development
    name: ${var.service_name}
    verison: 1.0.0

---

