apiVersion: dns.flexibleengine.upbound.io/v1beta1
kind: Recordset
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1beta1/recordset
  labels:
    testing.upbound.io/example-name: example_dns_recordset
  name: example-dns-recordset
spec:
  forProvider:
    description: An example record set
    name: rs.example-crossplane.com.
    records:
      - 10.0.0.1
    ttl: 3000
    type: A
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_dns_zone
