apiVersion: dws.flexibleengine.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: dws/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: example_dws_cluster
  name: example-dws-cluster
spec:
  forProvider:
    availabilityZone: eu-west-0a
    name: example_dws_cluster
    nodeType: dws.d1.xlarge
    numberOfNode: 3
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_secgroup
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet
    userNameSecretRef:
      key: username
      name: example-dws-password
      namespace: crossplane-system
    userPwdSecretRef:
      key: password
      name: example-dws-password
      namespace: crossplane-system
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_vpc
    publicIp:
      - publicBindType: not_use

    
